---
- name: 'Configure plugins repository'
  yum_repository:
    name: "Foreman plugins {{ foreman_scap_client_release }}"
    description: "Foreman plugins repository"
    baseurl: "{{ foreman_scap_client_repo_url }}"
    gpgcheck: "{{ foreman_scap_client_repo_gpg }}"
    state: "{{ foreman_scap_client_repo_state }}"

- name: 'Install the foreman_scap_client package'
  yum:
    name: "rubygem-foreman_scap_client"
    state: "{{ foreman_scap_client_ensure }}"

- name: 'Create cron in /etc/cron.d/'
  template:
    src: "{{ foreman_scap_client_cron_template }}"
    dest: /etc/cron.d/foreman_scap_client_cron
    owner: root

- name: 'Create config.yaml in /etc/foreman_scap_client'
  template:
    src: templates/config.yaml.j2
    dest: /etc/foreman_scap_client/config.yaml
    owner: root
